In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score

Data Preparation
---
---

In [3]:
df = pd.read_csv('course_lead_scoring_2026.csv')
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [4]:
# Check missing values
df.isna().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [5]:
# Fill missing values in categorial features
categorical_features = df.select_dtypes(include=['object']).columns
for column in categorical_features:
    df[column] = df[column].fillna('NA')

df.isna().sum()

lead_source                   0
industry                      0
employment_status             0
location                      0
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [6]:
# Fill missing values in numeric features
numeric_features = df.select_dtypes(include=['float']).columns
for column in numeric_features:
    df[column] = df[column].fillna(0.0)

df.isna().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

Q1. Most frequent observation (mode)
---
---

In [7]:
df['industry'].value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

The answer is 'technology'

Q2. The Biggest Correlation Matrix
---
---

In [ ]:
dataframe = pd.DataFrame(df, columns=['interaction_count', 'lead_score', 'number_of_courses_viewed', 'annual_income'])
dataframe.corr()

,interaction_count,lead_score,number_of_courses_viewed,annual_income
interaction_count,1.000000,0.915746,0.721609,0.122842
lead_score,0.915746,1.000000,0.757204,0.229496
number_of_courses_viewed,0.721609,0.757204,1.000000,0.161300
annual_income,0.122842,0.229496,0.161300,1.000000

The biggest correlation is `interaction_count` and `lead_score`

Split the Data
---
---

In [13]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

Q3. The biggest mutual information score with `converted`
---
---

In [21]:
def mutual_info_converted_score(series):
    return mutual_info_score(series, df_full_train.converted)

mutual_info_all = df_full_train[categorical_features].apply(mutual_info_converted_score)
mutual_info_all.sort_values(ascending=False)

lead_source          0.034761
employment_status    0.020313
industry             0.002898
location             0.001050
dtype: float64

The biggest mutual information score with `converted` is `lead_source`

Split the Data
---
---