In [1]:
import numpy as np
import pandas as pd

Q1. Pandas version
---
---

In [2]:
pd.__version__

'3.0.6'

Q2. Records count
---
---

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

Q3. Fuel types
---
---

In [4]:
df['fuel_type'].values.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Q4. Missing Values
---
---

In [5]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency
---
---

In [6]:
df[
    df['origin'] == 'Asia'
]['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6. Median value of horsepower
---
---

In [7]:
# Find the median value of the `horsepower` column in the dataset
df['horsepower'].median()

np.float64(254.0)

In [8]:
mode_hp = df['horsepower'].mode()[0]

In [9]:
df['horsepower'] = df['horsepower'].fillna(mode_hp)

In [10]:
df['horsepower'].isnull().sum()

np.int64(0)

In [11]:
# Find the median value of the `horsepower` column after fill missing values 
df['horsepower'].median()

np.float64(252.0)

Q7. Sum of weights
---
---

In [64]:
df_asia = df[df['origin'] == 'Asia'].copy()
X = df_asia[['vehicle_weight', 'model_year']].head(7)
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [65]:
XTX = X.T

In [66]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = (-XTX) * XTX * y
w

,2,6,8,10,15,16,22
vehicle_weight,-19775360000,-24148930000,-14314320000,-17582760000,-15602500000,-24818750000,-23763000000
model_year,-4382417600,-5158483200,-3190407200,-3521235600,-4028049000,-4492885100,-4891633200